<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="PRG_TEST" Id="{152e68d5-965f-4c54-a511-098a773e86b5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	HeatingCurve_Test : FC_HeatingCurve_Test;							 
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>