<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="PRG_TEST" Id="{b7aacc06-295a-4dea-ac85-460d15a60691}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>