# Demo CI workflow with TcUnit-Runner
name: TcUnit-Runner
 
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
 
jobs:
 
  tcunit_runner:
 
    # a self hosted runner, i.e. VM with tag 'tcunit'
    runs-on: [ self-hosted, E380 ]
 
    steps:
 
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Run TcUnit-Runner
        shell: cmd
        # Start TcUnit-Runner with a timeout of 5 min
        run: '"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat" -U 5'

      - name: Run local hosted Runner
        shell: cmd
        # Start github action runner on local machine
        run: "C:\actions-runner\actions-runner-win-x64-2.290.1\run.cmd"


      - uses: KyleAure/junit-report-annotations-action@1.5
        if: always()
        with:
          name: results TcUnit tests
          path: ${{ github.workspace }}/**/TcUnit_xUnit_results.xml          
          access-token: ${{ secrets.GITHUB_TOKEN }}